### ISSUE TITLE
SFR Period data TS-file cause forrtl: error (65): floating invalid

### ISSUE THREAD

**Issue by nikobenho** [MODFLOW-USGS/modflow6#863]
Hi,

I'm developing a 2D DISV model using SFR to represent a creek flowing through the model domain. Of interest are predictions pertaining to SW/GW exchange and stream flow rate. In order to history-match against measured data I need to represent rainfall and evaporation (perhaps runoff too) on a reach by reach basis.

I'm using the LUMPREM model to populate the TS-files with rainfall and evaporation data, which I then, on a record by record basis, parameterize for adjustment with PEST before running MF6.

However, I've found that sometimes MF6 crashes due to the `forrtl: error (65): floating invalid` error, causing termination of the entire calibration run:

![error](https://user-images.githubusercontent.com/46219250/150485685-ce6a0a8a-e185-4eaf-b6a2-fda27c0382f7.PNG)

I've been able to pinpoint the error to the TS-file containing rainfall data (I've run the model successfully > 30k times using only the evaporation TS file). Unfortunately I dont know what is causing the error. Ive found that the following input is invalid (see below), but changing the first entry (period 0.00000000) from 0.05000000 to 0.04900000 makes the error go away:

![tsfile](https://user-images.githubusercontent.com/46219250/150486076-9b9a5ab5-5eb2-478d-9112-c498b04584e9.PNG)

Any idea of what is causing the error, or suggestions for how to work around them (perhaps assigning values for stress period 0 is a problem?) is greatly appreciated, as I can't seem to get a better fit with measurements without parameterizing reach rainfall.

Cheers,
Nikolas

**Comment by langevin-usgs** [comment]
Hello @nikobenho, I see you are using an older version of MODFLOW 6.  Version 6.2.2 has been released, and we are close to releasing version 6.3.  Can you try this problem with version 6.2.2?  And if that doesn't work, then please also try with our develop version of the code, which can be downloaded here (https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases).  We've made some improvements to time series over the past year, so hopefully your problem is fixed.  If not, it would be great if you could post a minimally sized working model that demonstrates the problem.  You can drag a zip file of that model onto this issue here, and we will take a look.

**Comment by nikobenho** [comment]
Hi @langevin-usgs ,

The problem persisted when I used version 6.2.2. However, trying the nightly build seemed to fix the issue for me (~30k model runs without any errors). 

Thanks for your help 😄
